name: Windows Test Build

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Build
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pillow
          pip install pyinstaller
          pyinstaller --additional-hooks-dir=hooks --onefile --windowed --icon=dictate_wizard.icns --name "Dictate Wizard" main.py
        env:
          KIVY_GL_BACKEND: angle_sdl2
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Dictate Wizard
          path: dist/*
