name: Build and Package Kivy App for Windows

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
        
    - name: Download and extract Mesa
      run: |
        Invoke-WebRequest -Uri "https://github.com/pal1000/mesa-dist-win/releases/download/23.1.2/mesa3d-23.1.2-release-mingw.7z" -OutFile "mesa.7z"
        7z x "mesa.7z" -o"mesa"
        
    - name: Add Mesa to PATH
      run: echo "mesa\mesa3d-23.1.2-release-mingw\x86" >> $GITHUB_PATH
      
    - name: Set LIBGL_ALWAYS_SOFTWARE=1
      run: echo "LIBGL_ALWAYS_SOFTWARE=1" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --additional-hooks-dir=hooks --onefile --windowed --icon=dictate_wizard.icns --name "Dictate Wizard" main.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Dictate Wizard
        path: dist/*
