name: Build and Package Kivy App for Windows

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install 7zip
      run: choco install 7zip.install
      
    - name: Install Mesa
      shell: cmd
      run: |
        curl.exe -L --output mesa.7z --url https://github.com/pal1000/mesa-dist-win/releases/download/23.1.2/mesa3d-23.1.2-release-msvc.7z
        "C:\Program Files\7-Zip\7z.exe" x mesa.7z
        mklink "%GITHUB_WORKSPACE%\opengl32.dll" "%GITHUB_WORKSPACE%\x64\opengl32.dll"
        mklink "%GITHUB_WORKSPACE%\libglapi.dll" "%GITHUB_WORKSPACE%\x64\libglapi.dll"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Debug DLLs
      shell: cmd
      run: |
        dir "%GITHUB_WORKSPACE%"
        echo PATH=%PATH%

    - name: Build with PyInstaller
      run: |
        pyinstaller --additional-hooks-dir=hooks --onefile --windowed --icon=dictate_wizard.icns --name "Dictate Wizard" main.py
      env:
        PATH: "${{ env.PATH }};%GITHUB_WORKSPACE%"   
        
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Dictate Wizard
        path: dist/*
